#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=Run_model
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=5:00:00
#SBATCH --output=/gpfs/home2/choynck/thesis/ABM_based_LLMS/slurm_output_%A.out

module purge
module load 2025
module load CUDA/12.8.0
cd ~/thesis/ABM_based_LLMS/
source .venv_vllm/bin/activate

# Check whether the GPU is available
srun python -uc "import torch; print('GPU available?', torch.cuda.is_available())"
PYTHONPATH=src srun python -m utils.prompt_optimizer --seeds 53 --num-steps 8 --batch-size 7 --val-sample-size 20 --test-sample-size 120 --resume
