#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=Run_model
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=/gpfs/home2/choynck/thesis/ABM_based_LLMS/slurm_output_%A.out

module purge
module load 2025
module load CUDA/12.8.0
cd ~/thesis/ABM_based_LLMS/
source .venv_vllm/bin/activate
export PYTHONPATH="$PYTHONPATH:$(pwd)/src"

# Check whether the GPU is available
srun python -uc "import torch; print('GPU available?', torch.cuda.is_available())"
# PYTHONPATH=src srun python -m utils.prompt_optimizer --seeds 26 --num-steps 8 --batch-size 7 --val-sample-size 40 --test-sample-size 100 --mode phq9
PYTHONPATH=src python -m utils.prompt_optimizer --mode phq9-rerun-test --seeds 23 24 25 --instruction-filename optimized_instruction.txt
