#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=2
#SBATCH --job-name=Run_model
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=09:00:00
#SBATCH --output=/gpfs/home2/choynck/thesis/ABM_based_LLMS/slurm_output_%A.out

module purge
cd ~/thesis/ABM_based_LLMS/
source .venv_vllm/bin/activate

# Check whether the GPU is available
srun python -uc "import torch; print('GPU available?', torch.cuda.is_available())"

srun bash scripts/simulation/run_simulation_sdc.sh
