#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=2
#SBATCH --job-name=Run_model
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=02:00:00
#SBATCH --output=/gpfs/home2/choynck/thesis/ABM_based_LLMS/slurm_output_%A.out

module purge
cd ~/thesis/ABM_based_LLMS/
source .venv_vllm/bin/activate

# Check whether the GPU is available

srun bash scripts/sensitivity/sa_phq9_minimal_run.sh
