"""Standalone CLI entry points for building post datasets.

Each module here is invoked as a script:

    python -m utils.create_data.generate_synthetic_dataset ...
    python -m utils.create_data.generate_posts_opt_h ...
    python -m utils.create_data.generate_test_data ...
    python -m utils.create_data.generate_posts_grok ...

Shared loaders live in :mod:`_common`.
"""
