"""Dataset construction: persona builders + standalone post-generation CLIs.

Each module here is invoked as a script:

    python -m utils.create_data.build_persona_phq9_eval ...   # step 0: shared (persona, phq9) eval file
    python -m utils.create_data.build_test_personas ...
    python -m utils.create_data.build_finetune_personas ...
    python -m utils.create_data.generate_synthetic_dataset ...
    python -m utils.create_data.generate_posts_opt_h ...
    python -m utils.create_data.generate_test_data ...
    python -m utils.create_data.generate_posts_grok ...

Shared loaders live in :mod:`loaders`.
"""
